spring.application.name=backend

# backend/src/main/resources/application.properties
server.port=8080

# --- Oracle XE(Remote) ---
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@192.168.0.61:1521/XE
# (XE 11g라면) spring.datasource.url=jdbc:oracle:thin:@192.168.0.61:1521:XE
spring.datasource.username=farmday
spring.datasource.password=a123

# --- MyBatis ---
mybatis.mapper-locations=classpath*:mappers/**/*.xml
mybatis.type-aliases-package=com.farmday.test
mybatis.configuration.map-underscore-to-camel-case=false
mybatis.configuration.jdbc-type-for-null=NULL

# (Optional) SQL 로그가 필요하면 아래 주석 해제
# logging.level.com.farmday=DEBUG
# logging.level.org.mybatis=DEBUG

# === JWT 설정 ===
# 최소 32자 이상 아무 문자열로 만들어 줘야 함 (영문+숫자 섞어서)
jwt.secret=ThisIsAFarmdayJwtSecretKey_ChangeMe_123456

# Access Token 유효기간: 15분 (밀리초)
# jwt.access-token-validity-in-ms=900000
jwt.access-token-validity-in-ms=86400000

# Refresh Token 유효기간: 7일 (밀리초)
jwt.refresh-token-validity-in-ms=604800000

# 관리자 가입용 인증코드 (마음대로 정해도 됨)
admin.signup.code=FARMDAY-ADMIN-1234

# ✅ DevTools 옵션(기본값이지만 명시 추천)
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

# MyBatis XML 등 리소스 경로를 추가 감시하고 싶다면:
spring.devtools.restart.additional-paths=src/main/java,src/main/resources

app.frontend-url=http://192.168.0.20:5173
app.backend-url=http://192.168.0.20:8080

# ✅ 이미지 업로드 서버 전용
app.image-upload-url=http://192.168.0.76:8080/api/images/upload

# 정적 리소스는 재시작 대신 브라우저 리로드(기본 제외 규칙 유지 가능)
# spring.devtools.restart.exclude=static/**,public/**,templates/**

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=id8558@gmail.com
spring.mail.password=kbub cbux kukq wnob
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# --- KAMIS API (가격 수집용, PriceFetchService에서 사용) ---
kamis.api-url=https://www.kamis.or.kr/service/price/xml.do
kamis.api-key=188d5225-72c9-4fc7-8fb7-1e11f6f0a0d6
kamis.api-id=6818

# 단일 파일 최대 5MB
spring.servlet.multipart.max-file-size=5MB

# 전체 요청(여러 파일 합산) 최대 20MB
spring.servlet.multipart.max-request-size=20MB

# AWS 기본 설정
aws.region=us-east-2
aws.s3.bucket=yoonho-bucket

logging.level.com.farmday.price=DEBUG